"""
Configuration file for the Fixed Automation Weather Agent.

This file contains all the configuration settings for the agent.
In a real-world scenario, these would typically be loaded from
environment variables or a configuration file.
"""

# API Configuration
API_KEY = "your_openweathermap_api_key_here"  # Replace with your actual API key
CITY = "London"  # Default city to fetch weather for

# Output Configuration
OUTPUT_DIR = "weather_reports"  # Directory to save weather reports

# Agent Configuration
AGENT_NAME = "Fixed Automation Weather Agent"
AGENT_VERSION = "1.0.0"
AGENT_TYPE = "Level -1: Fixed Automation"

# API Settings
API_BASE_URL = "http://api.openweathermap.org/data/2.5/weather"
API_TIMEOUT = 10  # seconds
API_UNITS = "metric"  # metric, imperial, or kelvin

# Report Settings
REPORT_FORMAT = "text"  # text, json, or html
INCLUDE_TIMESTAMP = True
INCLUDE_AGENT_INFO = True

# Error Handling (Fixed Automation has limited error handling)
MAX_RETRIES = 0  # Fixed automation doesn't retry
RETRY_DELAY = 0  # No delay between retries
FAIL_ON_ERROR = True  # Always fail on error (no recovery)

# Logging
LOG_LEVEL = "INFO"
LOG_FORMAT = "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
LOG_FILE = "weather_agent.log"

# Schedule (for automated runs)
SCHEDULE_ENABLED = False  # Set to True to enable scheduled runs
SCHEDULE_INTERVAL = 3600  # Run every hour (in seconds)
SCHEDULE_START_TIME = "00:00"  # Start time for scheduled runs

# Weather Data Fields to Include
INCLUDE_FIELDS = [
    'temperature',
    'feels_like',
    'humidity',
    'pressure',
    'description',
    'wind_speed'
]

# Report Template (Fixed - no customization)
REPORT_TEMPLATE = """
WEATHER REPORT
==============
City: {city}, {country}
Date: {timestamp}

Current Conditions:
- Temperature: {temperature}°C
- Feels Like: {feels_like}°C
- Humidity: {humidity}%
- Pressure: {pressure} hPa
- Description: {description}
- Wind Speed: {wind_speed} m/s

Report generated by {agent_name}
"""

# Fixed Automation Characteristics
# These demonstrate the limitations of fixed automation
FIXED_AUTOMATION_LIMITATIONS = [
    "Cannot adapt to unexpected inputs",
    "Cannot make decisions based on weather conditions",
    "Cannot learn from past interactions",
    "Cannot handle API failures gracefully",
    "Cannot customize output based on user preferences",
    "Cannot integrate with other systems",
    "Cannot provide personalized recommendations"
]

# When to Use Fixed Automation
SUITABLE_USE_CASES = [
    "Simple, repetitive tasks",
    "Well-defined inputs and outputs",
    "Tasks that don't require decision-making",
    "High-volume, low-complexity operations",
    "Scheduled data collection",
    "Basic report generation"
]

# When NOT to Use Fixed Automation
UNSUITABLE_USE_CASES = [
    "Tasks requiring decision-making",
    "Handling unexpected inputs",
    "Learning from experience",
    "Adapting to changing conditions",
    "Complex problem-solving",
    "User interaction",
    "Error recovery"
]
